"""
Intelligence Fusion — agentic cross-module correlation on a single case.

When the scam classifier confirms an active session, fusion chains the other
Prahari modules on the same incident, the way a human analyst would work a
case across desks:

    1. scam verdict (already computed by the caller)
    2. fraud-graph lookup — is the caller number known mule-ring infrastructure?
    3. geospatial correlation — which active cluster does this pattern sit in?
    4. MHA / I4C alert packaging (generated by the scam module)
    5. hash-sealed ledger entry binding all of the above (chain-of-custody)

Every step reports what it found and its measured latency, so the fused
package stays glass-box end to end.
"""

from __future__ import annotations

import time
from typing import Dict, Optional

import audit
import data
import fraud_graph
import geospatial


def _ms(t0: float) -> float:
    return round((time.perf_counter() - t0) * 1000, 1)


def run(risk_score: int, verdict: str, stage_reached: str,
        caller_number: Optional[str], text_sha256: Optional[str] = None) -> Dict:
    steps = []
    case_id = f"CASE-{int(time.time()) % 100000:05d}"

    # 1. Detection (input to the fusion chain)
    steps.append({
        "title": "Scam classifier verdict",
        "status": "hit",
        "detail": f"{verdict} at risk {risk_score}/100 — kill-chain: {stage_reached}",
        "ms": 0.0,
    })

    # 2. Fraud-graph infrastructure lookup
    t0 = time.perf_counter()
    num = (caller_number or "").replace(" ", "").replace("-", "")
    graph_match: Dict = {"matched": False}
    if num:
        intel = fraud_graph.analyze(data.FRAUD_RECORDS)
        node_id = f"phone:{num}"
        camp = next((c for c in intel["campaigns"] if node_id in set(c.get("nodes", []))), None)
        if camp:
            role = "kingpin" if node_id in camp.get("kingpin_nodes", []) else "member"
            graph_match = {
                "matched": True, "node": node_id, "role": role,
                "campaign": camp["campaign_id"], "risk_index": camp["risk_index"],
                "victims": camp["victim_count"], "mule_accounts": camp["linked_accounts"],
                "loss": camp["estimated_loss_str"],
            }
            status, detail = "hit", (
                f"{num} is a {role.upper()} node of {camp['campaign_id']} — "
                f"risk {camp['risk_index']}, {camp['victim_count']} victims, "
                f"{camp['linked_accounts']} mule accounts, {camp['estimated_loss_str']} projected loss"
            )
        else:
            status, detail = "watch", (
                f"{num} not in known fraud infrastructure — pushed to telecom watchlist "
                f"({len(intel['graph']['nodes'])} nodes checked)"
            )
    else:
        status, detail = "watch", "No caller number supplied — script template hashed to watchlist"
    steps.append({"title": "Fraud-graph cross-reference", "status": status,
                  "detail": detail, "ms": _ms(t0)})

    # 3. Geospatial correlation
    t0 = time.perf_counter()
    geo = geospatial.analyze(data.GEO_POINTS)
    da_points = [p for p in data.GEO_POINTS if p["type"] == "digital_arrest"]
    hot = max(da_points, key=lambda p: p["intensity"])
    rank = next((h for h in geo["patrol_priority"] if h["location"] == hot["label"]), None)
    detail = f"Pattern matches active digital-arrest cluster: {hot['label']} (intensity {hot['intensity']}/10"
    if rank:
        detail += f", patrol priority #{rank['rank']}, {rank['recommended_units']} units advised"
    detail += ")"
    steps.append({"title": "Geospatial correlation", "status": "ok",
                  "detail": detail, "ms": _ms(t0)})

    # 4. Alert packaging (produced by the scam module alongside the verdict)
    steps.append({"title": "MHA / I4C alert package", "status": "ok",
                  "detail": "Alert package attached with full evidence trail — "
                            "routed to I4C; TSP asked to hold outbound transfers 30 min",
                  "ms": 0.1})

    # 5. Seal the fused case in the tamper-evident ledger
    t0 = time.perf_counter()
    entry = audit.log(
        "fusion",
        {"case_id": case_id, "caller": num or None, "verdict": verdict,
         "risk": risk_score, "graph": graph_match, "hotspot": hot["label"],
         "input_sha256": text_sha256},
        f"FUSED_{verdict}", risk_score,
        extra={"campaign": graph_match.get("campaign")},
    )
    steps.append({"title": "Sealed in tamper-evident ledger", "status": "ok",
                  "detail": f"Entry #{entry['seq']} · hash {entry['entry_hash'][:18]}… — "
                            f"binds verdict, graph match and geo context in one chain-of-custody record",
                  "ms": _ms(t0)})

    return {"case_id": case_id, "graph_match": graph_match, "steps": steps}
